# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/QA_Project',
                'doc_host': 'https://c123ian.github.io',
                'git_url': 'https://github.com/c123ian/QA_Project',
                'lib_path': 'QA_Project'},
  'syms': {'QA_Project.core': {'QA_Project.core.foo': ('core.html#foo', 'QA_Project/core.py')}}}
